### ISSUE TITLE
How to make a test for iprange ?

### ISSUE THREAD

**Issue by jcbf** [jsarenik/spf-tools#129]
How do you think is the beste way to test iprange.sh , assuming that iprange may not exists and , depending on that, may have diferent results ?

**Comment by jsarenik** [comment]
@jcbf I think that the test itself can check for the presence of `iprange` and expect the results of `iprange.sh` script accordingly. But I would not really go this far because it is third party and though it is nice to support it, it should not be considered to be part of `spf-tools` and be tested by our tests. How about this?

**Comment by jcbf** [comment]
ok. I just mentioned because I'm doing some  experiments with code coverage and hoping to have all code covered or at least, most of it.
I'm still fighting with travis to get it work so testing iprange.sh is just a detail .
